apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fuseki-tdb2
  namespace: packagegraph
  labels:
    app: fuseki
    app.kubernetes.io/name: fuseki
    app.kubernetes.io/part-of: packagegraph
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: topolvm-provisioner
  resources:
    requests:
      storage: 60Gi
