//! Gate: every ontology term this crate emits must be declared by the ontology,
//! in the role the emitting code uses it in.
//!
//! The collectors build predicate and class URIs as `format!("{PKG}fooBar")`,
//! hundreds of times across the tree. Nothing connected those strings to the
//! ontology, so a typo and a deliberately invented predicate looked identical,
//! and neither failed anything. `rpm:rpmProvides` reached 6,558,436 triples
//! that no consumer can discover from the published ontology.
//!
//! This module closes that loop at `cargo test` time by scanning the crate's
//! own source for writer calls, resolving each namespace prefix via the
//! constants in `uris.rs`, and checking the resulting URI against
//! `ontology-vocab.txt` (generated by `etl/scripts/gen-ontology-vocab.py`).
//!
//! ## Roles, not just spellings
//!
//! The first version of this gate compared bare URIs, which answered "is this
//! string declared?" but not "is it declared as the kind of thing you are
//! using it as?". `rpm:RPMGroup` slipped through on exactly that distinction:
//! it is a declared `owl:Class`, and `rpm.rs` and `emit/rpm_ext.rs` write it as
//! a literal predicate. A membership test calls that fine; it is 523,728
//! triples asserting a class URI as a property.
//!
//! So argument position decides what is required:
//!
//! | Position | Required role |
//! |---|---|
//! | predicate (arg 1 of every `write_*`) | `property` |
//! | object of `RDF_TYPE` | `class` |
//! | any other object | `class` or `individual` |
//!
//! ## Scope of the scan
//!
//! Only whole-string forms count: `format!("{PKG}packageName")` where the term
//! runs from the prefix to the closing quote. Collectors also build *instance*
//! URIs from these namespaces -- `format!("{TAX}audience-{slug}")` -- and those
//! name individuals the data creates, not vocabulary the ontology declares.
//!
//! `#[cfg(test)]` modules are skipped. Terms referenced only from test
//! fixtures are not emitted into any graph, and counting them overstates what
//! the collectors actually produce.
//!
//! It is a ratchet, not a clean bill of health: what was already wrong when
//! this landed is listed in `KNOWN_BAD` so the gate can pass today while
//! refusing anything new. Each entry is annotated with what is actually wrong
//! with it, so the list is the work queue.

#[cfg(test)]
mod tests {
    use std::collections::{HashMap, HashSet};
    use std::fs;
    use std::path::{Path, PathBuf};

    /// How a term is being used at a call site, which is what determines the
    /// role the ontology has to declare.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
    enum UsedAs {
        /// Predicate position: the ontology must declare a property.
        Property,
        /// Object of `rdf:type`: the ontology must declare a class.
        Class,
        /// Any other object position: a class or an individual will do.
        Value,
        /// The term is built away from its writer call -- into a variable, a
        /// lookup table, or a struct field -- so its role cannot be read off a
        /// call site. `debian.rs:965` is the case that forced this: the
        /// `deb:debDepends` family is assembled in a dependency-kind table and
        /// passed to `write_triple` through a variable, so a purely positional
        /// scan reports 1.46M triples' worth of predicates as absent.
        ///
        /// These are checked for declaration only. That is a genuinely weaker
        /// check, and it is named rather than hidden: this gate does not claim
        /// role coverage it does not have.
        Unknown,
    }

    impl UsedAs {
        fn label(self) -> &'static str {
            match self {
                UsedAs::Property => "property",
                UsedAs::Class => "class",
                UsedAs::Value => "value",
                UsedAs::Unknown => "unknown-role",
            }
        }

        fn satisfied_by(self, roles: &HashSet<String>) -> bool {
            match self {
                UsedAs::Property => roles.contains("property"),
                UsedAs::Class => roles.contains("class"),
                UsedAs::Value => roles.contains("class") || roles.contains("individual"),
                UsedAs::Unknown => !roles.is_empty(),
            }
        }
    }

    /// Terms this crate emits that the ontology does not declare in the role
    /// used, as of the 2026-09-11 audit. Each entry is either a term the
    /// ontology should declare or an emission the collectors should stop
    /// making. Nothing may be ADDED here: a new entry means new undeclared
    /// vocabulary or a new role violation, which is what this gate prevents.
    ///
    /// `rpm#RPMGroup` is the one role violation rather than an omission -- a
    /// declared class written as a predicate. Its remedy is a real property
    /// (`rpm:inGroup`) pointing at an `rpm:RPMGroup` instance, not a
    /// declaration.
    const KNOWN_BAD: &[(&str, &str)] = &[
        // bitbake
        ("https://purl.org/packagegraph/ontology/bitbake#inherits", "property"),
        // bsdpkg
        ("https://purl.org/packagegraph/ontology/bsdpkg#BinaryPackage", "class"),
        ("https://purl.org/packagegraph/ontology/bsdpkg#abi", "property"),
        ("https://purl.org/packagegraph/ontology/bsdpkg#flatsize", "property"),
        ("https://purl.org/packagegraph/ontology/bsdpkg#origin", "property"),
        // buildroot
        ("https://purl.org/packagegraph/ontology/buildroot#infrastructure", "property"),
        // chocolatey
        ("https://purl.org/packagegraph/ontology/chocolatey#downloadCount", "property"),
        // declared as nuget:isPrerelease (domain nuget:NuGetPackage;
        // a ChocolateyPackage is not a subclass of it)
        ("https://purl.org/packagegraph/ontology/chocolatey#isPrerelease", "property"),
        // core
        ("https://purl.org/packagegraph/ontology/core#Contribution", "class"),
        ("https://purl.org/packagegraph/ontology/core#EmailObservation", "class"),
        ("https://purl.org/packagegraph/ontology/core#architectureName", "property"),
        ("https://purl.org/packagegraph/ontology/core#checksum", "property"),
        ("https://purl.org/packagegraph/ontology/core#contributor", "property"),
        ("https://purl.org/packagegraph/ontology/core#displayName", "property"),
        ("https://purl.org/packagegraph/ontology/core#distributionName", "property"),
        ("https://purl.org/packagegraph/ontology/core#hasEmailObservation", "property"),
        ("https://purl.org/packagegraph/ontology/core#hasRepository", "property"),
        ("https://purl.org/packagegraph/ontology/core#isPhantomPackage", "property"),
        // declared as vcs:observedAt (domain vcs:ForgeVersionObservation;
        // this subject is a pkg:EmailObservation)
        ("https://purl.org/packagegraph/ontology/core#observedAt", "property"),
        ("https://purl.org/packagegraph/ontology/core#observedEmail", "property"),
        ("https://purl.org/packagegraph/ontology/core#releaseOrigin", "property"),
        ("https://purl.org/packagegraph/ontology/core#releaseSuite", "property"),
        ("https://purl.org/packagegraph/ontology/core#repository", "property"),
        // declared as deb:/rpm:versionConstraint (domain deb:Dependency);
        // emitted generically by emit/rdf.rs for every ecosystem
        ("https://purl.org/packagegraph/ontology/core#versionConstraint", "property"),
        // deb
        ("https://purl.org/packagegraph/ontology/deb#debConflicts", "unknown-role"),
        // role not statically determined: built in the dependency-kind
        // table at debian.rs:965 and passed through a variable.
        ("https://purl.org/packagegraph/ontology/deb#debDepends", "unknown-role"),
        ("https://purl.org/packagegraph/ontology/deb#debProvides", "property"),
        ("https://purl.org/packagegraph/ontology/deb#debRecommends", "unknown-role"),
        ("https://purl.org/packagegraph/ontology/deb#debSuggests", "unknown-role"),
        // declared as flatpak:/opkg:installedSize (domain flatpak:FlatpakApp)
        ("https://purl.org/packagegraph/ontology/deb#installedSize", "property"),
        // flatpak
        ("https://purl.org/packagegraph/ontology/flatpak#runtime", "property"),
        // maven
        ("https://purl.org/packagegraph/ontology/maven#type", "property"),
        // metrics
        ("https://purl.org/packagegraph/ontology/metrics#languageBytes", "property"),
        ("https://purl.org/packagegraph/ontology/metrics#primaryLanguage", "property"),
        ("https://purl.org/packagegraph/ontology/metrics#totalBytes", "property"),
        // nix
        ("https://purl.org/packagegraph/ontology/nix#NixPackage", "class"),
        ("https://purl.org/packagegraph/ontology/nix#attrPath", "property"),
        ("https://purl.org/packagegraph/ontology/nix#broken", "property"),
        // rpm
        // a declared owl:Class written as a predicate. Remedy is a real
        // property (rpm:inGroup) pointing at an rpm:RPMGroup instance, not a
        // declaration. 523,728 triples.
        ("https://purl.org/packagegraph/ontology/rpm#RPMGroup", "property"),
        ("https://purl.org/packagegraph/ontology/rpm#rpmConflicts", "property"),
        ("https://purl.org/packagegraph/ontology/rpm#rpmObsoletes", "property"),
        ("https://purl.org/packagegraph/ontology/rpm#rpmProvides", "property"),
        ("https://purl.org/packagegraph/ontology/rpm#rpmRequires", "property"),
        // vcs
        ("https://purl.org/packagegraph/ontology/vcs#commitCount", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#diskUsageKB", "property"),
        // declared as core:hasRelease (domain :Distribution, range
        // :DistributionRelease -- a distro release, not a forge release)
        ("https://purl.org/packagegraph/ontology/vcs#hasRelease", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#headCommitHash", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#isArchived", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#isFork", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#lastActivityDate", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#openIssuesCount", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#openPullRequestCount", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#projectHomepage", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#repositoryBrowser", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#repositoryCreatedAt", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#repositoryDescription", "property"),
        // declared as core:repositoryStatus (domain :Repository, the
        // package repository, not the VCS one)
        ("https://purl.org/packagegraph/ontology/vcs#repositoryStatus", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#repositoryURL", "property"),
        ("https://purl.org/packagegraph/ontology/vcs#topic", "property"),
        // xbps
        ("https://purl.org/packagegraph/ontology/xbps#revision", "property"),
    ];

    /// Writer methods whose argument 2 is an RDF object (so the term names a
    /// class or an individual). Every other `write_*` method puts a literal
    /// there, which is not a term.
    const OBJECT_ARG_METHODS: &[&str] = &[
        "write_triple",
        "write_triple_once",
        "write_bnode_subject",
        "write_bnode_to_bnode",
        "write_bnode_object",
    ];

    /// Map the namespace constants in uris.rs (`PKG`, `RPM`, ...) to their URIs
    /// by parsing uris.rs, so this never drifts from the real definitions.
    fn namespace_map(src: &Path) -> HashMap<String, String> {
        let text = fs::read_to_string(src.join("uris.rs")).expect("read uris.rs");
        let mut map = HashMap::new();
        for line in text.lines() {
            let Some(rest) = line.trim().strip_prefix("pub const ") else {
                continue;
            };
            let Some((name, value)) = rest.split_once(": &str = ") else {
                continue;
            };
            let uri = value.trim().trim_end_matches(';').trim_matches('"');
            if uri.starts_with("https://purl.org/packagegraph/") && uri.ends_with('#') {
                map.insert(name.trim().to_string(), uri.to_string());
            }
        }
        assert!(
            map.contains_key("PKG"),
            "did not find the PKG namespace constant in uris.rs"
        );
        map
    }

    /// Remove `#[cfg(test)]` items by brace matching, so test-only references
    /// are not counted as emitted vocabulary.
    fn strip_test_modules(text: &str) -> String {
        let mut out = String::with_capacity(text.len());
        let mut rest = text;
        while let Some(pos) = rest.find("#[cfg(test)]") {
            out.push_str(&rest[..pos]);
            let after = &rest[pos..];
            // Skip to the opening brace of the item, then past its matching close.
            let Some(open) = after.find('{') else { break };
            let mut depth = 0usize;
            let mut end = None;
            for (i, c) in after[open..].char_indices() {
                match c {
                    '{' => depth += 1,
                    '}' => {
                        depth -= 1;
                        if depth == 0 {
                            end = Some(open + i + 1);
                            break;
                        }
                    }
                    _ => {}
                }
            }
            match end {
                Some(e) => rest = &after[e..],
                None => break,
            }
        }
        out.push_str(rest);
        out
    }

    /// Split a call's argument list on top-level commas, respecting nesting and
    /// string literals.
    fn split_args(s: &str) -> Vec<String> {
        let mut args = Vec::new();
        let mut cur = String::new();
        let (mut depth, mut in_str, mut esc) = (0i32, false, false);
        for c in s.chars() {
            if in_str {
                cur.push(c);
                if esc {
                    esc = false;
                } else if c == '\\' {
                    esc = true;
                } else if c == '"' {
                    in_str = false;
                }
                continue;
            }
            match c {
                '"' => {
                    in_str = true;
                    cur.push(c);
                }
                '(' | '[' | '{' => {
                    depth += 1;
                    cur.push(c);
                }
                ')' | ']' | '}' => {
                    depth -= 1;
                    cur.push(c);
                }
                ',' if depth == 0 => {
                    args.push(cur.trim().to_string());
                    cur = String::new();
                }
                _ => cur.push(c),
            }
        }
        if !cur.trim().is_empty() {
            args.push(cur.trim().to_string());
        }
        args
    }

    /// Pull the single `{PREFIX}Term` a whole-string `format!` argument builds,
    /// if that is what this argument is.
    fn term_of(arg: &str, ns: &HashMap<String, String>) -> Option<String> {
        let open = arg.find('{')?;
        let close = arg[open..].find('}')? + open;
        let base = ns.get(&arg[open + 1..close])?;
        let after = &arg[close + 1..];
        let end = after
            .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
            .unwrap_or(after.len());
        // Must run to the closing quote, or it is an instance URI, not a term.
        if end == 0 || after.as_bytes().get(end) != Some(&b'"') {
            return None;
        }
        Some(format!("{base}{}", &after[..end]))
    }

    /// Every (term, usage) pair this crate emits.
    ///
    /// Two passes, because neither alone is both complete and role-aware:
    /// a positional pass over writer call sites yields roles, and a whole-file
    /// pass yields every term including those assembled away from their call
    /// site. Terms only the second pass finds are recorded as
    /// [`UsedAs::Unknown`] rather than dropped.
    fn emitted(src: &Path, ns: &HashMap<String, String>) -> HashSet<(String, UsedAs)> {
        let mut out = HashSet::new();
        let mut all_terms: HashSet<String> = HashSet::new();
        let mut files = Vec::new();
        collect_rs(src, &mut files);
        for f in files {
            if f.file_name().is_some_and(|n| n == "vocab.rs") {
                continue;
            }
            let text = strip_test_modules(&fs::read_to_string(&f).expect("read source"));

            // Pass 2 (completeness): any whole-string `format!("{PREFIX}Term")`
            // anywhere in the file, wherever it is later used.
            for (idx, _) in text.match_indices('{') {
                let tail = &text[idx..];
                if let Some(t) = term_of(tail, ns) {
                    all_terms.insert(t);
                }
            }

            // Pass 1 (roles): writer call sites, by argument position.
            for (idx, _) in text.match_indices(".write_") {
                let tail = &text[idx + 1..];
                let Some(paren) = tail.find('(') else { continue };
                let method = &tail[..paren];
                if !method
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '_')
                {
                    continue;
                }
                // Balanced extraction of the argument list.
                let body = &tail[paren + 1..];
                let (mut depth, mut in_str, mut esc, mut end) = (1i32, false, false, None);
                for (i, c) in body.char_indices() {
                    if in_str {
                        if esc {
                            esc = false;
                        } else if c == '\\' {
                            esc = true;
                        } else if c == '"' {
                            in_str = false;
                        }
                        continue;
                    }
                    match c {
                        '"' => in_str = true,
                        '(' | '[' | '{' => depth += 1,
                        ')' | ']' | '}' => {
                            depth -= 1;
                            if depth == 0 {
                                end = Some(i);
                                break;
                            }
                        }
                        _ => {}
                    }
                }
                let Some(e) = end else { continue };
                let args = split_args(&body[..e]);
                if args.len() < 2 {
                    continue;
                }
                // Argument 1 is the predicate for every write_* method.
                if let Some(t) = term_of(&args[1], ns) {
                    out.insert((t, UsedAs::Property));
                }
                if args.len() >= 3 && OBJECT_ARG_METHODS.contains(&method) {
                    if let Some(t) = term_of(&args[2], ns) {
                        let role = if args[1].contains("RDF_TYPE") {
                            UsedAs::Class
                        } else {
                            UsedAs::Value
                        };
                        out.insert((t, role));
                    }
                }
            }
        }

        // Anything the completeness pass found but no call site explained.
        let positioned: HashSet<&String> = out.iter().map(|(t, _)| t).collect();
        let unknown: Vec<String> = all_terms
            .iter()
            .filter(|t| !positioned.contains(t))
            .cloned()
            .collect();
        for t in unknown {
            out.insert((t, UsedAs::Unknown));
        }
        out
    }

    fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
        for e in fs::read_dir(dir).expect("read_dir") {
            let p = e.expect("dir entry").path();
            if p.is_dir() {
                collect_rs(&p, out);
            } else if p.extension().is_some_and(|x| x == "rs") {
                out.push(p);
            }
        }
    }

    /// Parse the role-annotated manifest.
    fn declared() -> HashMap<String, HashSet<String>> {
        let manifest = Path::new(env!("CARGO_MANIFEST_DIR")).join("ontology-vocab.txt");
        let text = fs::read_to_string(&manifest).unwrap_or_else(|e| {
            panic!(
                "cannot read {}: {e}. Regenerate with etl/scripts/gen-ontology-vocab.py",
                manifest.display()
            )
        });
        let mut out = HashMap::new();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (uri, roles) = line
                .split_once('\t')
                .unwrap_or_else(|| panic!("manifest line is not <uri>\\t<roles>: {line}"));
            out.insert(
                uri.to_string(),
                roles.split(',').map(|r| r.trim().to_string()).collect(),
            );
        }
        assert!(!out.is_empty(), "manifest parsed to zero terms");
        out
    }

    #[test]
    fn every_emitted_term_is_declared_in_the_role_it_is_used_in() {
        let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let ns = namespace_map(&src);
        let declared = declared();
        let known: HashSet<(&str, &str)> = KNOWN_BAD.iter().copied().collect();
        let empty = HashSet::new();

        let mut bad: Vec<String> = emitted(&src, &ns)
            .into_iter()
            .filter(|(uri, used)| {
                let roles = declared.get(uri).unwrap_or(&empty);
                !used.satisfied_by(roles) && !known.contains(&(uri.as_str(), used.label()))
            })
            .map(|(uri, used)| {
                let roles = declared.get(&uri).unwrap_or(&empty);
                if roles.is_empty() {
                    format!("{uri}\n    used as {}, but not declared at all", used.label())
                } else {
                    let mut have: Vec<_> = roles.iter().cloned().collect();
                    have.sort();
                    format!(
                        "{uri}\n    used as {}, but the ontology declares it only as {}",
                        used.label(),
                        have.join(", ")
                    )
                }
            })
            .collect();
        bad.sort();

        assert!(
            bad.is_empty(),
            "{} ontology term(s) are emitted in a role the ontology does not declare.\n\n{}\n\n\
             Either declare them in packagegraph/ontology and regenerate \
             etl/pg-collect/ontology-vocab.txt, or stop emitting them that way. Do NOT add \
             them to KNOWN_BAD -- that list only shrinks.",
            bad.len(),
            bad.join("\n")
        );
    }

    /// The ratchet only holds if its baseline stays accurate: an entry that has
    /// since been declared, or is no longer emitted that way, must be removed,
    /// or the list stops being a to-do and becomes noise.
    #[test]
    fn known_bad_list_has_no_stale_entries() {
        let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let ns = namespace_map(&src);
        let declared = declared();
        let emitted = emitted(&src, &ns);
        let empty = HashSet::new();

        let mut stale = Vec::new();
        for (uri, used_label) in KNOWN_BAD {
            let used = match *used_label {
                "property" => UsedAs::Property,
                "class" => UsedAs::Class,
                "value" => UsedAs::Value,
                "unknown-role" => UsedAs::Unknown,
                other => panic!("KNOWN_BAD has an unknown usage role {other:?} for {uri}"),
            };
            if !emitted.contains(&(uri.to_string(), used)) {
                stale.push(format!("{uri} ({used_label}) -- no longer emitted that way"));
            } else if used.satisfied_by(declared.get(*uri).unwrap_or(&empty)) {
                stale.push(format!("{uri} ({used_label}) -- now declared in that role"));
            }
        }
        stale.sort();

        assert!(
            stale.is_empty(),
            "{} stale KNOWN_BAD entr(ies) -- remove them:\n{}",
            stale.len(),
            stale.join("\n")
        );
    }
}
