//! Gate: every ontology term this crate emits must be declared by the ontology.
//!
//! The collectors build predicate and class URIs as `format!("{PKG}fooBar")`,
//! 926 times across the tree. Nothing connected those strings to the ontology,
//! so a typo and a deliberately invented predicate looked identical, and
//! neither failed anything. The 2026-09-11 production audit found 28
//! properties and 2 classes emitted at volume that the ontology never
//! declares -- `rpm:rpmProvides` alone is 6,558,436 triples that no consumer
//! can discover from the published ontology.
//!
//! This module closes that loop at `cargo test` time by scanning the crate's
//! own source for those `format!` patterns, resolving the namespace prefix via
//! the constants in `uris.rs`, and checking each resulting URI against
//! `ontology-vocab.txt` (generated by `etl/scripts/gen-ontology-vocab.py`).
//!
//! Scanning source rather than querying the graph doubled the count, to 60:
//! the graph only shows terms whose code path actually ran in a production
//! collection, so every undeclared term behind an unrun branch was invisible.
//! It also exposed a class the graph cannot show at all -- six terms whose
//! local name IS declared, but in another module and scoped by `rdfs:domain`
//! to a different class, so the emission is wrong even though the name
//! resolves. `vcs:hasRelease` is the clearest: `core:hasRelease` exists, with
//! domain `:Distribution` and range `:DistributionRelease` -- Debian 12, not a
//! GitHub release. Those are annotated in `KNOWN_UNDECLARED` below; none of
//! them is fixable by swapping the prefix.
//!
//! It is a ratchet, not a clean bill of health: the terms already undeclared
//! when this landed are listed in `KNOWN_UNDECLARED` so the gate can pass
//! today while refusing anything new. Shrinking that list is tracked in
//! `docs/reports/2026-09-11-ontology-conformance-and-coverage-audit.md`.

#[cfg(test)]
mod tests {
    use std::collections::{HashMap, HashSet};
    use std::fs;
    use std::path::Path;

    /// The 60 terms emitted by this crate that the ontology does not declare,
    /// as of 2026-09-11. Each is either a term the ontology should declare or
    /// an emission the collectors should stop making -- see finding 5 of the
    /// audit report. Nothing may be ADDED to this list: a new entry means new
    /// undeclared vocabulary, which is the thing this gate exists to prevent.
    const KNOWN_UNDECLARED: &[&str] = &[
        // bitbake
        "https://purl.org/packagegraph/ontology/bitbake#inherits",
        // bsdpkg
        "https://purl.org/packagegraph/ontology/bsdpkg#BinaryPackage",
        "https://purl.org/packagegraph/ontology/bsdpkg#abi",
        "https://purl.org/packagegraph/ontology/bsdpkg#flatsize",
        "https://purl.org/packagegraph/ontology/bsdpkg#origin",
        // buildroot
        "https://purl.org/packagegraph/ontology/buildroot#infrastructure",
        // chocolatey
        "https://purl.org/packagegraph/ontology/chocolatey#downloadCount",
        // same local name exists as nuget:isPrerelease (domain nuget:NuGetPackage; choco:ChocolateyPackage is not a subclass)
        "https://purl.org/packagegraph/ontology/chocolatey#isPrerelease",
        // core
        "https://purl.org/packagegraph/ontology/core#Contribution",
        "https://purl.org/packagegraph/ontology/core#EmailObservation",
        "https://purl.org/packagegraph/ontology/core#architectureName",
        "https://purl.org/packagegraph/ontology/core#checksum",
        "https://purl.org/packagegraph/ontology/core#contributor",
        "https://purl.org/packagegraph/ontology/core#displayName",
        "https://purl.org/packagegraph/ontology/core#distributionName",
        "https://purl.org/packagegraph/ontology/core#hasEmailObservation",
        "https://purl.org/packagegraph/ontology/core#hasRepository",
        "https://purl.org/packagegraph/ontology/core#isPhantomPackage",
        // same local name exists as vcs:observedAt (domain vcs:ForgeVersionObservation; this subject is a pkg:EmailObservation)
        "https://purl.org/packagegraph/ontology/core#observedAt",
        "https://purl.org/packagegraph/ontology/core#observedEmail",
        "https://purl.org/packagegraph/ontology/core#releaseOrigin",
        "https://purl.org/packagegraph/ontology/core#releaseSuite",
        "https://purl.org/packagegraph/ontology/core#repository",
        "https://purl.org/packagegraph/ontology/core#upstreamPackageVersion",
        // same local name exists as deb:/rpm:versionConstraint (domain deb:Dependency; emitted generically for all ecosystems)
        "https://purl.org/packagegraph/ontology/core#versionConstraint",
        // deb
        "https://purl.org/packagegraph/ontology/deb#debConflicts",
        "https://purl.org/packagegraph/ontology/deb#debDepends",
        "https://purl.org/packagegraph/ontology/deb#debProvides",
        "https://purl.org/packagegraph/ontology/deb#debRecommends",
        "https://purl.org/packagegraph/ontology/deb#debSuggests",
        // same local name exists as flatpak:/opkg:installedSize (domain flatpak:FlatpakApp)
        "https://purl.org/packagegraph/ontology/deb#installedSize",
        // flatpak
        "https://purl.org/packagegraph/ontology/flatpak#runtime",
        // maven
        "https://purl.org/packagegraph/ontology/maven#type",
        // metrics
        "https://purl.org/packagegraph/ontology/metrics#languageBytes",
        "https://purl.org/packagegraph/ontology/metrics#primaryLanguage",
        "https://purl.org/packagegraph/ontology/metrics#totalBytes",
        // nix
        "https://purl.org/packagegraph/ontology/nix#NixPackage",
        "https://purl.org/packagegraph/ontology/nix#attrPath",
        "https://purl.org/packagegraph/ontology/nix#broken",
        // rpm
        "https://purl.org/packagegraph/ontology/rpm#rpmConflicts",
        "https://purl.org/packagegraph/ontology/rpm#rpmObsoletes",
        "https://purl.org/packagegraph/ontology/rpm#rpmProvides",
        "https://purl.org/packagegraph/ontology/rpm#rpmRequires",
        // vcs
        "https://purl.org/packagegraph/ontology/vcs#commitCount",
        "https://purl.org/packagegraph/ontology/vcs#diskUsageKB",
        // same local name exists as core:hasRelease (domain :Distribution, range :DistributionRelease -- a distro release, not a forge release)
        "https://purl.org/packagegraph/ontology/vcs#hasRelease",
        "https://purl.org/packagegraph/ontology/vcs#headCommitHash",
        "https://purl.org/packagegraph/ontology/vcs#isArchived",
        "https://purl.org/packagegraph/ontology/vcs#isFork",
        "https://purl.org/packagegraph/ontology/vcs#lastActivityDate",
        "https://purl.org/packagegraph/ontology/vcs#openIssuesCount",
        "https://purl.org/packagegraph/ontology/vcs#openPullRequestCount",
        "https://purl.org/packagegraph/ontology/vcs#projectHomepage",
        "https://purl.org/packagegraph/ontology/vcs#repositoryBrowser",
        "https://purl.org/packagegraph/ontology/vcs#repositoryCreatedAt",
        "https://purl.org/packagegraph/ontology/vcs#repositoryDescription",
        // same local name exists as core:repositoryStatus (domain :Repository, the package repository, not the VCS one)
        "https://purl.org/packagegraph/ontology/vcs#repositoryStatus",
        "https://purl.org/packagegraph/ontology/vcs#repositoryURL",
        "https://purl.org/packagegraph/ontology/vcs#topic",
        // xbps
        "https://purl.org/packagegraph/ontology/xbps#revision",
    ];

    /// Map the namespace constants in uris.rs (`PKG`, `RPM`, ...) to their URIs
    /// by parsing uris.rs, so this never drifts from the real definitions.
    fn namespace_map(src: &Path) -> HashMap<String, String> {
        let text = fs::read_to_string(src.join("uris.rs")).expect("read uris.rs");
        let mut map = HashMap::new();
        for line in text.lines() {
            let line = line.trim();
            let Some(rest) = line.strip_prefix("pub const ") else {
                continue;
            };
            let Some((name, value)) = rest.split_once(": &str = ") else {
                continue;
            };
            let uri = value.trim().trim_end_matches(';').trim_matches('"');
            if uri.starts_with("https://purl.org/packagegraph/") && uri.ends_with('#') {
                map.insert(name.trim().to_string(), uri.to_string());
            }
        }
        assert!(
            map.contains_key("PKG"),
            "did not find the PKG namespace constant in uris.rs"
        );
        map
    }

    /// Extract every `format!("{PREFIX}Term")` occurrence from the crate source.
    ///
    /// Only whole-string forms count: the term must run from the prefix to the
    /// closing quote. Collectors also build *instance* URIs from the same
    /// namespaces -- `format!("{TAX}audience-{slug}")`,
    /// `format!("{PKG}match-repology-{id}")` -- and those name individuals the
    /// data creates, not vocabulary the ontology is expected to declare.
    /// Requiring the closing quote is what separates the two.
    fn emitted_terms(src: &Path, ns: &HashMap<String, String>) -> HashSet<String> {
        let mut out = HashSet::new();
        let mut files: Vec<_> = Vec::new();
        collect_rs(src, &mut files);
        for f in files {
            // This file quotes `{PKG}fooBar` in its own documentation.
            if f.file_name().is_some_and(|n| n == "vocab.rs") {
                continue;
            }
            let text = fs::read_to_string(&f).expect("read source file");
            for (idx, _) in text.match_indices("{") {
                let tail = &text[idx + 1..];
                let Some(close) = tail.find('}') else { continue };
                let prefix = &tail[..close];
                let Some(base) = ns.get(prefix) else { continue };
                let after = &tail[close + 1..];
                let end = after
                    .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
                    .unwrap_or(after.len());
                if end == 0 || after.as_bytes().get(end) != Some(&b'"') {
                    continue;
                }
                out.insert(format!("{base}{}", &after[..end]));
            }
        }
        out
    }

    fn collect_rs(dir: &Path, out: &mut Vec<std::path::PathBuf>) {
        for e in fs::read_dir(dir).expect("read_dir") {
            let p = e.expect("dir entry").path();
            if p.is_dir() {
                collect_rs(&p, out);
            } else if p.extension().is_some_and(|x| x == "rs") {
                out.push(p);
            }
        }
    }

    fn declared() -> HashSet<String> {
        let manifest = Path::new(env!("CARGO_MANIFEST_DIR")).join("ontology-vocab.txt");
        let text = fs::read_to_string(&manifest).unwrap_or_else(|e| {
            panic!(
                "cannot read {}: {e}. Regenerate with etl/scripts/gen-ontology-vocab.py",
                manifest.display()
            )
        });
        text.lines()
            .map(str::trim)
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .map(str::to_string)
            .collect()
    }

    #[test]
    fn every_emitted_term_is_declared_by_the_ontology() {
        let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let ns = namespace_map(&src);
        let declared = declared();
        let known: HashSet<&str> = KNOWN_UNDECLARED.iter().copied().collect();

        let mut undeclared: Vec<String> = emitted_terms(&src, &ns)
            .into_iter()
            .filter(|t| !declared.contains(t) && !known.contains(t.as_str()))
            .collect();
        undeclared.sort();

        assert!(
            undeclared.is_empty(),
            "{} ontology term(s) are emitted but not declared by the ontology.\n\n{}\n\n\
             Either declare them in packagegraph/ontology and regenerate \
             etl/pg-collect/ontology-vocab.txt, or stop emitting them. Do NOT add them to \
             KNOWN_UNDECLARED -- that list only shrinks.",
            undeclared.len(),
            undeclared.join("\n")
        );
    }

    /// The ratchet only holds if its baseline stays accurate: an entry that has
    /// since been declared (or is no longer emitted) must be removed, or the
    /// list silently stops being a to-do and starts being noise.
    #[test]
    fn known_undeclared_list_has_no_stale_entries() {
        let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let ns = namespace_map(&src);
        let declared = declared();
        let emitted = emitted_terms(&src, &ns);

        let now_declared: Vec<&str> = KNOWN_UNDECLARED
            .iter()
            .copied()
            .filter(|t| declared.contains(*t))
            .collect();
        let no_longer_emitted: Vec<&str> = KNOWN_UNDECLARED
            .iter()
            .copied()
            .filter(|t| !emitted.contains(*t))
            .collect();

        assert!(
            now_declared.is_empty(),
            "these are now declared by the ontology -- remove them from KNOWN_UNDECLARED:\n{}",
            now_declared.join("\n")
        );
        assert!(
            no_longer_emitted.is_empty(),
            "these are no longer emitted -- remove them from KNOWN_UNDECLARED:\n{}",
            no_longer_emitted.join("\n")
        );
    }
}
