apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuseki
  namespace: packagegraph
spec:
  template:
    spec:
      containers:
        - name: fuseki
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 4Gi
