apiVersion: batch/v1
kind: Job
metadata:
  name: etl-collect
  namespace: packagegraph
spec:
  template:
    spec:
      containers:
        - name: etl
          env:
            - name: HOME
              value: /tmp
            - name: REPO_URL
              value: "http://deb.debian.org/debian"
            - name: REPO_TYPE
              value: "debian"
            - name: COLLECT_ARCHES
              value: "binary-amd64"
            - name: COLLECT_ARGS
              value: "--dist stable --component main"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
