apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuseki
  namespace: packagegraph
spec:
  template:
    spec:
      containers:
        - name: fuseki
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
