apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuseki
  namespace: packagegraph
spec:
  template:
    spec:
      containers:
        - name: fuseki
          resources:
            requests:
              cpu: 500m
              memory: 3Gi
            limits:
              cpu: "2"
              memory: 6Gi
