apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: packagegraph

resources:
  - namespace.yaml
  # minio/secret.yaml — managed out-of-band via `oc create secret`
  - minio/pvc.yaml
  - minio/deployment.yaml
  - minio/service.yaml
  - fuseki/configmap.yaml
  - fuseki/pvc.yaml
  - fuseki/deployment.yaml
  - fuseki/service.yaml
  - fuseki/route.yaml
  - fuseki/read-replica.yaml
