apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qlever-data
  namespace: packagegraph
  labels:
    app: qlever
    app.kubernetes.io/name: qlever
    app.kubernetes.io/part-of: packagegraph
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: topolvm-provisioner
  resources:
    requests:
      storage: 20Gi
