apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: packagegraph
type: Opaque
stringData:
  MINIO_ENDPOINT: "minio.example.com"
  MINIO_BUCKET: "packagegraph"
  MINIO_ACCESS_KEY: "CHANGEME"
  MINIO_SECRET_KEY: "CHANGEME"
