apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: packagegraph
type: Opaque
stringData:
  MINIO_ENDPOINT: "minio.packagegraph.svc:9000"
  MINIO_BUCKET: "packagegraph"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
