apiVersion: v1
kind: ServiceAccount
metadata:
  name: rebuild-tdb2
  namespace: packagegraph

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rebuild-tdb2
  namespace: packagegraph
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "watch"]
    resourceNames: ["fuseki"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rebuild-tdb2
  namespace: packagegraph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rebuild-tdb2
subjects:
  - kind: ServiceAccount
    name: rebuild-tdb2
    namespace: packagegraph
