#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["rdflib>=7"]
# ///
"""Generate etl/pg-collect/ontology-vocab.txt: every class and property the
ontology declares.

Why a checked-in manifest rather than reading the ontology at test time:
etl/ontology/ is populated by sync-ontology.sh at image-build time and is not
in the repository, so `cargo test` in CI has no ontology to read. A manifest
is also reviewable -- bumping etl/ONTOLOGY_VERSION produces a diff a human can
read, which is the point at which a renamed or removed term should be noticed.

Regenerate whenever etl/ONTOLOGY_VERSION changes:

    etl/scripts/gen-ontology-vocab.py --ontology-dir ../ontology

Shapes and examples are excluded deliberately: a term appearing only in a
*.shacl.ttl is not declared by the ontology, it is merely constrained by it.
The 2026-09-11 audit found nix:attrPath and nix:NixPackage in exactly that
state -- constrained by nix.shacl.ttl, declared nowhere.
"""

import argparse
import sys
from pathlib import Path

from rdflib import OWL, RDF, Graph, URIRef

PG_PREFIX = "https://purl.org/packagegraph/"

# Any packagegraph-namespace subject the ontology gives an rdf:type to is a term
# the ontology declares -- classes, properties, and named individuals alike.
# Enumerating only classes and properties misses individuals such as slsa:L2 and
# att:GPG, which collectors legitimately emit as object values.
# owl:Ontology subjects are the module IRIs themselves, not vocabulary.
NOT_VOCABULARY = {OWL.Ontology}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ontology-dir", type=Path, required=True)
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "pg-collect" / "ontology-vocab.txt",
    )
    args = ap.parse_args()

    mods = [
        f
        for f in sorted(args.ontology_dir.rglob("*.ttl"))
        if not f.name.endswith((".shacl.ttl", ".examples.ttl"))
    ]
    if not mods:
        sys.exit(f"no ontology modules under {args.ontology_dir}")

    g = Graph()
    for f in mods:
        g.parse(f)

    terms: set[str] = set()
    for s, _, t in g.triples((None, RDF.type, None)):
        if isinstance(s, URIRef) and str(s).startswith(PG_PREFIX) and t not in NOT_VOCABULARY:
            terms.add(str(s))

    version_file = args.out.resolve().parent.parent / "ONTOLOGY_VERSION"
    version = "unknown"
    if version_file.exists():
        for line in version_file.read_text().splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                version = line
                break

    body = "\n".join(sorted(terms))
    args.out.write_text(
        f"# Generated by etl/scripts/gen-ontology-vocab.py -- do not edit by hand.\n"
        f"# Ontology {version}, {len(mods)} modules. Shapes and examples excluded:\n"
        f"# a term constrained only by a *.shacl.ttl is not a declared term.\n"
        f"# Regenerate when etl/ONTOLOGY_VERSION changes.\n"
        f"{body}\n"
    )
    print(f"wrote {args.out} -- {len(terms)} declared terms from {len(mods)} modules ({version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
