"""Cross-language integration tests: Rust pg-collect ↔ Python rdflib"""

import pytest
from rdflib import Graph
import subprocess
import tempfile
from pathlib import Path


def test_rust_ntriples_parseable_by_rdflib():
    """Verify that Rust-generated N-Triples can be parsed by Python rdflib."""
    # This test requires the Rust binary to be built
    rust_binary = Path("../pg-collect/target/release/pg-collect")

    if not rust_binary.exists():
        pytest.skip(
            "Rust binary not built (run: cd ../pg-collect && cargo build --release)"
        )

    # We can't run a full collector test without a real or mock HTTP server
    # For now, just verify the binary exists and has correct help output
    result = subprocess.run(
        [str(rust_binary), "--help"],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0
    assert "PackageGraph bulk collector" in result.stdout
    assert "debian" in result.stdout
    assert "rpm" in result.stdout


def test_ntriples_format_structure():
    """Verify N-Triples format structure from unit tests."""
    # The actual N-Triples parsing is tested in Rust unit tests
    # and in the Debian/RPM collector unit tests
    #
    # This test documents that the Python side can parse N-Triples
    # generated by the Rust collectors

    # Sample N-Triples (matching what the Rust collector outputs)
    sample_nt = """
<https://packagegraph.github.io/data/package/debian/trixie/amd64/libc6/2.36-1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://purl.org/packagegraph/ontology/core#BinaryPackage> .
<https://packagegraph.github.io/data/package/debian/trixie/amd64/libc6/2.36-1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://purl.org/packagegraph/ontology/debian#BinaryPackage> .
<https://packagegraph.github.io/data/package/debian/trixie/amd64/libc6/2.36-1> <https://purl.org/packagegraph/ontology/core#packageName> "libc6" .
""".strip()

    with tempfile.NamedTemporaryFile(mode="w", suffix=".nt", delete=False) as f:
        f.write(sample_nt)
        temp_path = f.name

    try:
        g = Graph()
        g.parse(temp_path, format="nt")

        # Verify we loaded triples
        assert len(g) == 3

        # Verify dual typing is present
        from rdflib import URIRef, Namespace

        PKG = Namespace("https://purl.org/packagegraph/ontology/core#")
        DEB = Namespace("https://purl.org/packagegraph/ontology/debian#")

        pkg_uri = URIRef(
            "https://packagegraph.github.io/data/package/debian/trixie/amd64/libc6/2.36-1"
        )
        from rdflib.namespace import RDF

        assert (pkg_uri, RDF.type, PKG.BinaryPackage) in g
        assert (pkg_uri, RDF.type, DEB.BinaryPackage) in g
    finally:
        Path(temp_path).unlink()


def test_escaped_literals_parseable():
    """Verify that escaped N-Triples literals (newlines, quotes) parse correctly."""
    # Rust escapes: \\ \" \n \r \t
    sample_nt = r"""
<https://example.org/pkg/test> <https://example.org/description> "Line 1\nLine 2\tTabbed" .
<https://example.org/pkg/test> <https://example.org/quoted> "He said \"hello\"" .
""".strip()

    with tempfile.NamedTemporaryFile(mode="w", suffix=".nt", delete=False) as f:
        f.write(sample_nt)
        temp_path = f.name

    try:
        g = Graph()
        g.parse(temp_path, format="nt")

        assert len(g) == 2

        # Verify escaped content is correctly decoded
        from rdflib import URIRef

        pkg_uri = URIRef("https://example.org/pkg/test")
        desc_pred = URIRef("https://example.org/description")

        desc_values = list(g.objects(pkg_uri, desc_pred))
        assert len(desc_values) == 1
        assert "Line 1\nLine 2\tTabbed" == str(desc_values[0])
    finally:
        Path(temp_path).unlink()
